"""added uuid to message model, updated relations

Revision ID: 371eb68ed757
Revises: 9e7bb23c7de8
Create Date: 2024-11-04 21:34:10.306716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371eb68ed757'
down_revision: Union[str, None] = '9e7bb23c7de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_uuid', sa.UUID(), nullable=False))
    op.add_column('messages', sa.Column('sender_uuid', sa.UUID(), nullable=False))
    op.add_column('messages', sa.Column('uuid', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_messages_uuid'), 'messages', ['uuid'], unique=True)
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_uuid'], ['uuid'])
    op.create_foreign_key(None, 'messages', 'chats', ['chat_uuid'], ['uuid'])
    op.drop_column('messages', 'sender_id')
    op.drop_column('messages', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_index(op.f('ix_messages_uuid'), table_name='messages')
    op.drop_column('messages', 'uuid')
    op.drop_column('messages', 'sender_uuid')
    op.drop_column('messages', 'chat_uuid')
    # ### end Alembic commands ###
