"""replaced message model field with naive datetime

Revision ID: 4666afdefb86
Revises: 371eb68ed757
Create Date: 2024-11-04 22:01:44.877702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4666afdefb86'
down_revision: Union[str, None] = '371eb68ed757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
